kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "secondary-scheduler.serviceAccountName" . }}-system-kube-scheduler
subjects:
  - kind: ServiceAccount
    name: {{ include "secondary-scheduler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
