apiVersion: v1
kind: ConfigMap
metadata:
  name: secondary-scheduler-config
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: secondary-scheduler
      pluginConfig:
      - args:
          scoringStrategy:
            type: MostAllocated
        name: NodeResourcesFit
      plugins:
        score:
          disabled:
          - name: NodeResourcesBalancedAllocation
          enabled:
          - name: NodeResourcesFit
            weight: 5
